### ISSUE TITLE
"Avatars" of the user not being shown in the modern layout

### ISSUE THREAD

**Issue by DarkTexas** [ItsOnlyBinary/kiwiirc-plugin-custom-welcome-asl#5]
The Users "avatars" aren't shown in the "modern" layout.

Example:

https://gljclan.com/sd/uRaIB3SCAQ.png - that's how it should look
https://gljclan.com/sd/1Zj3dnXg8P.png - that's how it actually looks.

Thanks

**Comment by DarkTexas** [comment]
addition: There is an avatar for male, female etc. JUST not for those who have not selected ANY gender..

**Comment by ItsOnlyBinary** [comment]
this has been fixed in kiwiirc master ;)
